config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :products do
    member do
      get 'page'
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :title, presence: true
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:edit, :update, :show, :destroy, :page]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.description = product_params[:description].open.read if product_params[:description].present?
    if @product.save
      flash[:success] = 'Product created successfully'
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def edit

  end

  def update
    if @product.update_attributes(product_params)
      flash[:success] = 'Successfully updated'
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def show
    doc = Nokogiri::HTML.parse(@product.description)

    # filter ppc links
    # Start
    @ppc_links = doc.css("li.ads-ad h3 a")
    @ppc_links = @ppc_links.map { |link|  link}
    @ppc_links = @ppc_links - @ppc_links.map { |link|  link if %w{display:none}.include?link['style'] }
    # End

    # filter ppc links
    # Start
    @organic_links = doc.css(".med h3 a")
    @organic_links = @organic_links.map { |link|  link}
    @organic_links = @organic_links - @organic_links.map { |link|  link if %w{display:none}.include?link['style'] }
    # End
  end

  def page
    render layout: false
  end

  def destroy
    @product.destroy!
    flash[:success] = 'Successfully deleted'
    redirect_to action: :index
  end

  private

  def set_product
    @product = Product.find params[:id]
  end

  def product_params
    params.require(:product).permit(:title, :description)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ppc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'shared/header' %>
<div class="container-fluid">
  <%= render partial: 'shared/alerts' %>
  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
    <%= f.input :title %>
    <% if params[:action] == 'new' or  params[:action] == 'create' %>
        <%= f.input :description, as: :file, input_html: {'accept': 'text/html'} %>
    <% end %>

    <%= f.submit 'Save', class: 'btn btn-success' %>
<%- end %>

app/views/products/edit.html.erb
<div class="jumbotron ">
  <h1 class="text-center">Products</h1>
</div>

<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <%= render partial: 'form' %>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/products/index.html.erb
<div class="admin-main-con">
  <div class="jumbotron ">
    <h1 class="text-center">Products</h1>
  </div>
  <div class='col-xs-12'>
    <p class="text-right">
      <%= link_to 'New Product', new_product_path, class: 'btn btn-primary' %>
    </p>
    <div class="row">
      <div class="col-sm-12">
        <table class="table table-striped">
          <thead>
          <tr class="info">
            <th>ID</th>
            <th>Title</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @products.each do |product| %>
              <tr>
                <td><%= product.id %></td>
                <td><%= product.title.titleize %></td>
                <td>
                  <%= link_to page_product_path(product) do %>
                      <i class="fa fa-html5"></i>
                  <% end %>
                  <%= link_to product_path(product) do %>
                      <i class="fa fa-eye"></i>
                  <%- end %>
                  <%= link_to edit_product_path(product) do %>
                      <i class="fa fa-edit"></i>
                  <%- end %>
                  <%= link_to product_path(product), method: :delete, data: {confirm: 'Are you sure?'}, class: 'text-danger' do %>
                      <i class="fa fa-trash"></i>
                  <% end %>
                </td>
              </tr>
          <%- end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="jumbotron ">
  <h1 class="text-center">Products</h1>
</div>

<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <%= render partial: 'form' %>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/products/page.html.erb
<%= raw @product.description %>

app/views/products/show.html.erb
<div class="admin-main-con">
  <div class='col-xs-12'>
    <div class="row">
      <div class="col-sm-12">
        <h2><%= @product.title.titleize %></h2>
      </div>
      <div class="col-sm-12">
        <h4 class="text-danger">PPC links</h4>
        <hr>
        <% @ppc_links.each_with_index do |link, index| %>
            <strong><%= "#{index+1}) " %><%= raw link %></strong>
            <hr>
        <% end %>
        <h4 class="text-danger">Organic links</h4>
        <hr>
        <% @organic_links.each_with_index do |link, index| %>
            <strong><%="#{index+1}) " %> <%= raw link %></strong>
            <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_alerts.html.erb
<% if flash[:success].present? %>
    <div class="alert alert-success" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:success] %>
    </div>
<%- end %>

<% if flash[:info].present? %>
    <div class="alert alert-info" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:info] %>
    </div>
<%- end %>

<% if flash[:warning].present? %>
    <div class="alert alert-warning" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:warning] %>
    </div>
<%- end %>

<% if flash[:error].present? %>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:error] %>
    </div>
<%- end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="javascript:void(0)">SCO</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="<%= root_path %>">Home</a></li>
      <li><a href="<%= products_path %>">Products</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="javascript:void(0)">98766543210</a></li>
      <li><a href="javascript:void(0)">test@abc.com</a></li>
    </ul>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron ">
  <h1 class="text-center">Home Page</h1>
</div>
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4 text-center">
    <%= link_to 'Go to page Products', products_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-sm-4"></div>
</div>